---
title: "Group Project"
author: "Kushal Kundanmal"
date: "30/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
library(gghalves)
library(lubridate)
library(gridExtra)
library(sf)
library(vroom)
library(skimr)
library(janitor)
library(mice)
```


```{r}
# first select mobility data for our target cities
in_mob <-  vroom("2020_IN_Region_Mobility_Report.csv") %>% filter(sub_region_1=="Delhi")

gb_mob <- vroom("2020_GB_Region_Mobility_Report.csv") %>% filter(sub_region_1=="Greater London")

ch_mob <- vroom("2020_CH_Region_Mobility_Report.csv") %>% filter(sub_region_1=="Zurich")
```

```{r}
# select only past 36 months
london_air <- vroom("london-air-quality.csv") %>% 
  mutate(date = ymd(date),
         year = year(date)) %>% filter(date>=as.Date("2018-01-01"))

delhi_air <- vroom("delhi-institute of tool engineering, wazirpur, delhi, delhi, india-air-quality.csv") %>% 
  mutate(date = ymd(date),
         year = year(date)) %>% filter(date>=as.Date("2018-01-01"))

wuhan_air <- vroom("wuhan-air-quality.csv") %>% 
  mutate(date = ymd(date),
         year = year(date)) %>% filter(date>=as.Date("2018-01-01"))

zurich_air <- vroom("zurich-kaserne, switzerland-air-quality.csv") %>% 
  mutate(date = ymd(date),
         year = year(date)) %>% filter(date>=as.Date("2018-01-01"))

```

```{r}
# describe the mobility data
skim(gb_mob)

skim(ch_mob)

skim(in_mob)
```

```{r}
# describe/view air quality data

skim(london_air)

skim(zurich_air)

skim(wuhan_air)

skim(delhi_air)

```

```{r}
# check for dupes
london_air%>%get_dupes(date)
wuhan_air%>%get_dupes(date)
zurich_air %>%get_dupes(date)
delhi_air %>% get_dupes(date)

# dupes in mobility?
in_mob %>% get_dupes(date)
ch_mob %>% get_dupes(date)
gb_mob %>% get_dupes(date)

# fix duplicates across sub regions by averaging the values
in_mob_clean <- in_mob %>% group_by(date) %>% 
  summarise(retail_and_recreation_percent_change_from_baseline=mean(retail_and_recreation_percent_change_from_baseline),
                                        grocery_and_pharmacy_percent_change_from_baseline=mean(grocery_and_pharmacy_percent_change_from_baseline),
                                        parks_percent_change_from_baseline=mean(parks_percent_change_from_baseline),
                                        transit_stations_percent_change_from_baseline=mean(transit_stations_percent_change_from_baseline),
                                        workplaces_percent_change_from_baseline=mean(workplaces_percent_change_from_baseline),
                                        residential_percent_change_from_baseline=mean(residential_percent_change_from_baseline)) %>% ungroup()
gb_mob_clean <- gb_mob %>% group_by(date) %>% 
  summarise(retail_and_recreation_percent_change_from_baseline=mean(retail_and_recreation_percent_change_from_baseline),
                                        grocery_and_pharmacy_percent_change_from_baseline=mean(grocery_and_pharmacy_percent_change_from_baseline),
                                        parks_percent_change_from_baseline=mean(parks_percent_change_from_baseline),
                                        transit_stations_percent_change_from_baseline=mean(transit_stations_percent_change_from_baseline),
                                        workplaces_percent_change_from_baseline=mean(workplaces_percent_change_from_baseline),
                                        residential_percent_change_from_baseline=mean(residential_percent_change_from_baseline)) %>% ungroup()

```
```{r}
# lets look into missing data
md.pattern(in_mob_clean,rotate.names = T)

md.pattern(gb_mob_clean,rotate.names = T)

md.pattern(ch_mob,rotate.names = T)
```

```{r}
# merge the mobility and air quality data
lon_merged <- left_join(london_air,gb_mob_clean,by='date')

del_merged <- left_join(delhi_air,in_mob_clean,by='date')

zur_merged <- left_join(zurich_air,ch_mob,by='date')
```


```{r}
# some visualizations
lon_merged %>% ggplot(aes(x=date,y=pm25,color=year)) +
  geom_smooth() +
  geom_point()

del_merged %>% ggplot(aes(x=date,y=pm25,color=year)) +
  geom_smooth() +
  geom_point()

zur_merged %>% ggplot(aes(x=date,y=pm25,color=year)) +
  geom_smooth() +
  geom_point()

wuhan_air %>% ggplot(aes(x=date,y=pm25,color=year)) +
  geom_smooth() +
  geom_point()

```
```{r}
lon_long <- lon_merged %>% pivot_longer(cols=c(9:14),names_to="type",values_to="percent") %>% filter(date>=as.Date("2020-02-15"))
lon_long %>% ggplot(aes(x=date,y=percent,color=type)) +
  geom_smooth() +
  #geom_point() +
  NULL

del_long <- del_merged %>% pivot_longer(cols=c(9:14),names_to="type",values_to="percent") %>% filter(date>=as.Date("2020-02-15"))
del_long %>% ggplot(aes(x=date,y=percent,color=type)) +
  geom_smooth()

zur_long <- zur_merged %>% pivot_longer(cols=c(15:20),names_to="type",values_to="percent") %>% filter(date>=as.Date("2020-02-15"))
zur_long %>% ggplot(aes(x=date,y=percent,color=type)) +
  geom_smooth()

```

```{r}
# attempt one at percent change
del_pm2_averages <- del_merged %>% filter(year!=2020) %>% mutate(month=month(date),day=day(date)) %>% group_by(month,day) %>% summarise(base_pm25=mean(pm25))

del_long <- del_long %>% mutate(month=month(date),day=day(date)) %>%
  merge(.,del_pm2_averages,by=c("month","day")) %>%
  mutate(per_change_pm25=(pm25-base_pm25)/base_pm25*100)

lon_pm2_averages <- lon_merged %>% filter(year!=2020) %>% mutate(month=month(date),day=day(date)) %>% group_by(month,day) %>% summarise(base_pm25=mean(pm25))

lon_long <- lon_long %>% mutate(month=month(date),day=day(date)) %>%
  merge(.,del_pm2_averages,by=c("month","day")) %>%
  mutate(per_change_pm25=(pm25-base_pm25)/base_pm25*100)

zur_pm2_averages <- zur_merged %>% filter(year!=2020) %>%
  mutate(month=month(date),day=day(date)) %>% group_by(month,day) %>% summarise(base_pm25=mean(pm25))
zur_long <- zur_long %>% mutate(month=month(date),day=day(date)) %>%
  merge(.,del_pm2_averages,by=c("month","day")) %>%
  mutate(per_change_pm25=(pm25-base_pm25)/base_pm25*100)

```


```{r}
# attempt 2
del_merged2 <- del_merged %>% arrange(date) %>% mutate(prior_yr_pm25=lag(pm25,365),change_pm25=(pm25-prior_yr_pm25)/prior_yr_pm25*100)

del_merged %>%  group_by(month(date),year(date)) %>% summarize(monthly_change=mean(change_pm25)) 

# ggplot(aes(x=date,y=monthly_change)) +
#   geom_point() +
#   geom_smooth() +
#   ylim(-100,1000)

```



```{r}
# plot pm2 vs workplace percent change

del_long %>% 
  filter(date>=as.Date("2020-05-01")) %>% 
  ggplot(aes(y=per_change_pm25,x=percent)) +
  geom_smooth() + facet_wrap(~type,scales = "free")



lon_long %>% 
  filter(date>=as.Date("2020-05-01")) %>% 
  ggplot(aes(y=per_change_pm25,x=percent)) +
  geom_smooth() + facet_wrap(~type,scales = "free")


zur_long %>% 
  filter(date>=as.Date("2020-05-01")) %>% 
  ggplot(aes(y=per_change_pm25,x=percent)) +
  geom_smooth() + facet_wrap(~type,scales = "free")


```

```{r}
del_merged <- del_merged %>% mutate(month=month(date),day=day(date)) %>%
  merge(.,del_pm2_averages,by=c("month","day")) %>%
  mutate(per_change_pm25=(pm25-base_pm25)/base_pm25*100)
del_merged %>% 
  #filter(date>=as.Date("2020-01-01")) %>%
  ggplot(aes(y=per_change_pm25,x=date)) +
  geom_smooth()

lon_merged <- lon_merged %>% mutate(month=month(date),day=day(date)) %>%
  merge(.,del_pm2_averages,by=c("month","day")) %>%
  mutate(per_change_pm25=(pm25-base_pm25)/base_pm25*100)
lon_merged %>% 
  #filter(date>=as.Date("2020-01-01")) %>%
  ggplot(aes(y=per_change_pm25,x=date)) +
  geom_smooth()


zur_merged <- zur_merged %>% mutate(month=month(date),day=day(date)) %>%
  merge(.,del_pm2_averages,by=c("month","day")) %>%
  mutate(per_change_pm25=(pm25-base_pm25)/base_pm25*100)
zur_merged %>% 
  #filter(date>=as.Date("2020-01-01")) %>%
  ggplot(aes(y=per_change_pm25,x=date)) +
  geom_smooth()
```
```{r}
m1 <- zur_merged %>% mutate(month=month(date)) %>% lm(pm25 ~ retail_and_recreation_percent_change_from_baseline+
     grocery_and_pharmacy_percent_change_from_baseline+
     transit_stations_percent_change_from_baseline+
     retail_and_recreation_percent_change_from_baseline+
     workplaces_percent_change_from_baseline+
     residential_percent_change_from_baseline+
       month,na.action=na.omit,data=.)

summary(m1)
```

```{r}
#maybe try with log prices
library(caret)
library(rpart.plot)
control <- trainControl (
    method="cv",
    number=5,
    verboseIter=TRUE)
merged_nona <- del_merged %>% mutate(month=month(date))
model2_tree <- train(
  pm25 ~ retail_and_recreation_percent_change_from_baseline+
     grocery_and_pharmacy_percent_change_from_baseline+
     transit_stations_percent_change_from_baseline+
     retail_and_recreation_percent_change_from_baseline+
     workplaces_percent_change_from_baseline+
     residential_percent_change_from_baseline+
    month,
  merged_nona,
  method = "rpart",
  na.action = na.omit,
  trControl = control,
  tuneLength=10
    )

#You can view how the tree performs
model2_tree$results

#You can view the final tree
rpart.plot(model2_tree$finalModel)

#you can also visualize the variable importance
importance <- varImp(model2_tree, scale=TRUE)
plot(importance)


model2_tree$bestTune

```
```{r}
ggplot(del_merged,aes(y=pm25,x=retail_and_recreation_percent_change_from_baseline)) +
  geom_point() +
  geom_smooth()
```

